apiVersion: v1
kind: Service
metadata:
  name: fundamental-project
spec:
  selector:
    app: fundamental-project
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fundamental-project
  labels:
    app: fundamental-project
spec:
  replicas: 3
  selector:
    matchLabels:
      app: fundamental-project
  template:
    metadata:
      labels:
        app: fundamental-project
    spec:
      containers:
      - name: fundamental-project
        image: abroomfield/fundamental-project:latest
        ports:
        - containerPort: 5000
        env:
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: fundamental-project
              key: secretKey
        - name: DATABASE_URI
          valueFrom:
            secretKeyRef:
              name: fundamental-project
              key: databaseURI